apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-swhi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0038-tenant/tkrw-pr712-0075-0038-app/devfile-sample-swhi@sha256:65af58d0c0af54aca3171024855b2ccbdc5f08b607f8ca1a766f22915cf2daa3
        name: my-nodejs
        resources: {}
status: {}
